ktor:
  deployment:
    port: ${PORT:8080}
  application:
    modules:
      - com.bakingbuddy.plugins.DatabaseKt.configureDatabase
      - com.bakingbuddy.plugins.RoutingKt.configureRouting
      - com.bakingbuddy.plugins.SerializationKt.configureSerialization
      - com.bakingbuddy.plugins.StatusPageKt.configureStatusPages
      - com.bakingbuddy.plugins.OpenApiKt.configureOpenApi
