-- Migration unit 1: schema_changes
-- Transaction mode: transactional
-- Boundary reason: default

CREATE TYPE public.rating_category AS ENUM (
  'OVERALL',
  'TASTE',
  'TEXTURE',
  'APPEARANCE',
  'RISE_STRUCTURE',
  'CUSTOM'
);

CREATE TABLE public.bake_ratings (
  id             bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at     timestamp with time zone DEFAULT now() NOT NULL,
  bake_id        uuid                     DEFAULT gen_random_uuid() NOT NULL,
  overall        smallint,
  taste          smallint,
  texture        smallint,
  appearance     smallint,
  rise_structure smallint,
  difficulty     smallint
);

ALTER TABLE public.bake_ratings
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.bake_ratings
  ADD CONSTRAINT bake_ratings_bake_id_fkey FOREIGN KEY (bake_id) REFERENCES public.bakes(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE public.bake_ratings
  ADD CONSTRAINT bake_ratings_pkey PRIMARY KEY (id);

GRANT ALL ON public.bake_ratings TO anon;

GRANT ALL ON public.bake_ratings TO authenticated;

GRANT ALL ON public.bake_ratings TO service_role;

ALTER TABLE public.recipes
  ADD COLUMN favorite boolean DEFAULT false NOT NULL;

ALTER TABLE public.recipes
  ADD COLUMN difficulty_rating smallint;
